//轮播图数据       请加入banner轮播图片数据
bannerData = [
		"../images/banner/1.jpg",
		"../images/banner/2.jpg",
		"../images/banner/3.jpg"
]

//热门hot数据
hotData=[
	{
		id:90000000379,
		playTime:38702,
		src:"../images/hot/1.jpg",
		title:'泰国.曼谷',
		content:'Welcome to this beautiful town.at this place,u can feel the different culture.',
		t:'清迈——三人行',
	    by:'体验清迈，私享空间',
	    c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
		href:'../video/2.webm',
		uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
		id:90000000229,
		playTime:12702,
		src:"../images/hot/2.jpg",
		title:'泰国.曼谷',
		content:'Record every day with the video, wait until we are old, will leave a lot of precious memories.',
		t:'清迈——三人行',
	    by:'体验清迈，私享空间',
	    c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
		href:'../video/2.webm',
		uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
		id:90000001379,
		playTime:498702,
		src:"../images/hot/3.jpg",
		title:'泰国.曼谷',
		content:'The creation of fresh information is to let us see what happened in different cities in the world, for our free travel abroad to bring more reference, so that our travel is no longer blind.',
		t:'清迈——三人行',
	    by:'体验清迈，私享空间',
	    c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
		href:'../video/StockholmBigcitynight-HD-1.mp4',
		uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]





//Asian
AsianData=[
	{
	  id:10000000001,
	  playTime:418702,
	  src:'../images/dataImage/Asian/ip1.jpg',
	  title:'我和闺蜜的东京迪士尼之旅',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'日本——东京',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/3.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	},
	  	{
	  		headpic:'../images/headpic/3.jpg',
	  		name:'窝窝',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	}
	  ]
	},
	{
	  id:10000000002,
	  playTime:351702,
	  src:'../images/dataImage/Asian/ip2.png',
	  title:'沿途的向阳花——邂逅我的泰国女孩',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/4.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/3.jpg',
	  		name:'窝窝',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/4.jpg',
	  		name:'王二小',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000003,
      playTime:398702,
	  src:'../images/dataImage/Asian/ip3.jpg',
	  title:'探寻埃及神秘的美',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/2.webm',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000004,
      playTime:122702,
	  src:'../images/dataImage/Asian/ip4.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000005,
      playTime:18705,
	  src:'../images/dataImage/Asian/ip5.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000006,
      playTime:28722,
	  src:'../images/dataImage/Asian/ip6.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000007,
      playTime:18755,
	  src:'../images/dataImage/Asian/ip7.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000008,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip8.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000009,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip9.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000010,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip10.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000011,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip11.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000012,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip12.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000013,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip13.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000014,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip14.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000015,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip15.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000016,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip16.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000017,
      playTime:187302,
	  src:'../images/dataImage/Asian/ip17.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000018,
      playTime:287042,
	  src:'../images/dataImage/Asian/ip18.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000019,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip19.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000020,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip20.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000021,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip21.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000022,
      playTime:132702,
	  src:'../images/dataImage/Asian/ip22.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000023,
      playTime:13202,
	  src:'../images/dataImage/Asian/ip23.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000024,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip24.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000025,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip25.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000026,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip26.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000027,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip27.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000028,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip28.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:10000000029,
      playTime:18702,
	  src:'../images/dataImage/Asian/ip29.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
	
	
]

//Europe
EuropeData=[
	{
	  id:20000000001,	
	  playTime:318702,
	  src:'../images/dataImage/Europe/ip1.jpg',
	  title:'6月，与你与久与巴黎酒庄',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/4.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:20000000002,
	  playTime:218702,
	  src:'../images/dataImage/Europe/ip2.jpg',
	  title:'德国那些你不知道的小城市',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/5.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:20000000003,
	  playTime:118702,
	  src:'../images/dataImage/Europe/ip3.jpg',
	  title:'骑自行车玩转荷兰',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000004,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip4.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000005,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip5.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000006,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip6.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000007,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip7.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000008,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip8.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000009,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip9.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
      id:20000000010,
      playTime:18702,
	  src:'../images/dataImage/Europe/ip10.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]
//America
AmericaData=[
	{
	  id:30000000001,	
	  playTime:218702,
	  src:'../images/dataImage/America/ip1.jpg',
	  title:'假期就是和你和它和海洋与沙滩',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/6.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:30000000002,	
	  playTime:118702,
	  src:'../images/dataImage/America/ip2.jpg',
	  title:'自驾美国西北部，我想，这就是我想要的生活',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/8.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:30000000003,	
	  playTime:18702,
	  src:'../images/dataImage/America/ip3.jpg',
	  title:'谁说，坐飞机才是旅行——记录我的重机车澳洲旅',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]

//Africa
AfricaData=[
	{
	  id:40000000001,	
	  playTime:198702,
	  src:'../images/dataImage/Africa/ip1.jpg',
	  title:'那些在非洲与狮子为伍的日子',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/9.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:40000000002,	
	  playTime:118702,
	  src:'../images/dataImage/Africa/ip2.jpg',
	  title:'寻找亚马逊热带雨林失落的文化',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/7.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:40000000003,
	  playTime:28702,
	  src:'../images/dataImage/Africa/ip3.jpg',
	  title:'探寻非洲原始部落',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]

//poles
polesData=[
	{
	  id:50000000001,	
	  playTime:218702,
	  src:'../images/dataImage/poles/ip1.jpg',
	  title:'南极遇到罕见的帝王企鹅',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:50000000002,	
	  playTime:200702,
	  src:'../images/dataImage/poles/ip2.jpg',
	  title:'北极极光见证我们的爱情',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/2.webm',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:50000000003,	
	  playTime:118702,
	  src:'../images/dataImage/poles/ip3.jpg',
	  title:'泰国.曼谷',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]
//Ocean
OceanData=[
	{
	  id:60000000001,	
	  playTime:218702,
	  src:'../images/dataImage/Ocean/ip1.jpg',
	  title:'大西洋遇见鲸鱼群',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:60000000002,	
	  playTime:200702,
	  src:'../images/dataImage/Ocean/ip2.jpg',
	  title:'跨越太平洋来到南美洲游记',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/2.webm',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	},
	{
	  id:60000000003,	
	  playTime:188702,
	  src:'../images/dataImage/Ocean/ip3.jpg',
	  title:'首次开国产飞机飞跃赤道',
	  content:'Thailand ban posside Thailand ban possideThailand ban possideThailand ban possideThailand ban possideThailand ban posside',
	  t:'清迈——三人行',
	  by:'体验清迈，私享空间',
	  c:'私密的客房、国际化的标准、人性化的服务，打造一个只属于您和家人的独立私享空间。',
	  href:'../video/StockholmBigcitynight-HD-1.mp4',
	  uesrData:[
	  	{
	  		headpic:'../images/headpic/1.jpg',
	  		name:'Gina',
	  		content:'哈哈哈哈哈有趣就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉就设计是计算机世界上接啊接啊家沙拉是来捣乱的拉拉队思考思考思考思考考就设计是计算机世界上接啊接啊家沙拉是来捣乱的',
	  		like:999,
	  		say:10,
	  		collect:false,
	  		vip:'red'
	  	},
	  	{
	  		headpic:'../images/headpic/2.jpg',
	  		name:'Annie',
	  		content:'哈哈哈哈哈有趣就设计是计算机哈哈哈哈哈有趣就设计是计算机',
	  		like:999,
	  		say:20,
	  		collect:false,
	  		vip:'blue'
	  	}
	  ]
	}
]

//index主页显示的bg图片

//花瓣
bgData1 = [
	{
		num:1,
		name:'flower1',
		src:'../images/bg/a.png'
	},
	{
		num:2,
		name:'flower2',
		src:'../images/bg/b.png'
	},
	{
		num:3,
		name:'flower3',
		src:'../images/bg/c.png'
	},
	{
		num:4,
		name:'flower4',
		src:'../images/bg/d.png'
	},
	{
		num:5,
		name:'flower5',
		src:'../images/bg/e.png'
	},
	{
		num:6,
		name:'flower6',
		src:'../images/bg/f.png'
	},
	{
		num:7,
		name:'flower1',
		src:'../images/bg/a.png'
	},
	{
		num:8,
		name:'flower2',
		src:'../images/bg/b.png'
	},
	{
		num:9,
		name:'flower3',
		src:'../images/bg/c.png'
	},
	{
		num:10,
		name:'flower4',
		src:'../images/bg/d.png'
	},
	{
		num:11,
		name:'flower5',
		src:'../images/bg/e.png'
	},
	{
		num:12,
		name:'flower6',
		src:'../images/bg/f.png'
	},
	{
		num:13,
		name:'flower2',
		src:'../images/bg/b.png'
	},
	{
		num:14,
		name:'flower3',
		src:'../images/bg/c.png'
	},
	{
		num:15,
		name:'flower5',
		src:'../images/bg/e.png'
	},
	{
		num:16,
		name:'flower6',
		src:'../images/bg/f.png'
	},
	{
		num:17,
		name:'flower2',
		src:'../images/bg/b.png'
	},
	{
		num:18,
		name:'flower3',
		src:'../images/bg/c.png'
	},
	{
		num:19,
		name:'flower5',
		src:'../images/bg/e.png'
	},
	{
		num:20,
		name:'flower6',
		src:'../images/bg/f.png'
	}
]
//树叶
bgData2 = [
	{
		num:1,
		name:'leaf1橙色',
		src:'../images/bg/1.png'
	},
	{
		num:2,
		name:'leaf2棕色',
		src:'../images/bg/2.png'
	},
	{
		num:3,
		name:'leaf3褐色',
		src:'../images/bg/3.png'
	},
	{
		num:4,
		name:'leaf4',
		src:'../images/bg/4.png'
	},
	{
		num:5,
		name:'leaf5',
		src:'../images/bg/5.png'
	},
	{
		num:6,
		name:'leaf6',
		src:'../images/bg/6.png'
	},
	{
		num:7,
		name:'leaf7',
		src:'../images/bg/7.png'
	},
	{
		num:8,
		name:'leaf8',
		src:'../images/bg/8.png'
	},
	{
		num:9,
		name:'leaf9',
		src:'../images/bg/9.png'
	},
	{
		num:10,
		name:'leaf10',
		src:'../images/bg/10.png'
	}
]

//用户留言数据
uesrData = [
		{
			
		}
	]


